# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Threelogy
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  In a world dominated by highly scripted, acted out wedding videos, Threelogy has been steadfast and bullishly stubborn in keeping theris natural, candid and real. And we wouldn't have it any other way. And quite frankly, you should too.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
sass:
    style: :compressed

# Build settings
markdown: kramdown

collections:
  wedding:
    output: true
    permalink: /wedding/:path/



