
title: Threelogy
description: > # this means to ignore newlines until "baseurl:"
  In a world dominated by highly scripted, acted out wedding videos, Threelogy has been steadfast and bullishly stubborn in keeping theris natural, candid and real. And we wouldn't have it any other way. And quite frankly, you should too.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

version: 3.0.3

# Build settings
markdown: kramdown

sass:
    style: compressed

collections:
  video:
    output: true
    permalink: /reel/:path/




